name: zelosify-recruit-backend

services:
  postgres:
    image: postgres:17
    container_name: recruit-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testrun
      POSTGRES_DB: zelosify_recruit_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5445:5432" # Expose internal 5432 on host port 5445 (Port 5445 can be used to connect psql outside the container)
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: recruit-keycloak
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/zelosify_recruit_test
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=testrun
      - KC_DB_SCHEMA=public
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_TRANSACTION_XA_ENABLED=false
      - KC_CLUSTERING=disabled
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
      - KC_PROXY_HEADERS=forwarded
      - KC_DB_POOL_INITIAL_SIZE=1
      - KC_DB_POOL_MIN_SIZE=2
      - KC_DB_POOL_MAX_SIZE=5
      - KC_LOG_LEVEL=INFO,org.keycloak.services:debug
      - KC_SPI_PROTOCOL_OPENID_CONNECT_LEGACY_LOGOUT_REDIRECT_URI=true
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --http-enabled=true
      - --hostname-strict=false
      - --http-relative-path=/auth
      - --proxy-headers=forwarded
    networks:
      - backend_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend_net:
    driver: bridge

volumes:
  keycloak_data:
    driver: local
  postgres_data:
    driver: local
